healthUserID: 7226778021918831098
accessToken: ya29.a0AX07CmsZVzlYdL8gc6QudIJ3TEkwINKxvQoK7x_eFYi68eg2CqSGnIVT-IMs8CyLcFQKS7d4R-BcSacezFDLpOWhIXUqGGWarn_xQZXrqMekiX6gFnLTd10wFPdrUpigg0D8eymshucTUMbWpj7j7gdbSMzdVBB6QpkmyW8MfASfOl3voAPLv7qYiSVo22eMqLhHrUQaCgYKARQSARYSFQHGX2Mi_JJibgioS3tLHD2-zLB9cQ0206
refreshToken: 1//011EacsnMhFmJCgYIARAAGAESNwF-L9IrqmgLRMHFOF-oqK744co8ilNqahZxM24cOnizeaGesbFk4IO2Qbx1yqzTtq99nGraLTk
tokenType: Bearer
expiresAtEpochMs: 1791104347472
updatedAt: 2026-10-04T07:59:08.472552Z
scope: https://www.googleapis.com/auth/googlehealth.activity_and_fitness.writeonly
  https://www.googleapis.com/auth/googlehealth.location.readonly https://www.googleapis.com/auth/googlehealth.reproductive_health.readonly
  https://www.googleapis.com/auth/googlehealth.sleep.readonly https://www.googleapis.com/auth/googlehealth.settings.readonly
  https://www.googleapis.com/auth/googlehealth.sleep.writeonly https://www.googleapis.com/auth/googlehealth.logged_symptoms.readonly
  https://www.googleapis.com/auth/googlehealth.activity_and_fitness.readonly https://www.googleapis.com/auth/googlehealth.health_metrics_and_measurements.readonly
  https://www.googleapis.com/auth/googlehealth.mindfulness.readonly https://www.googleapis.com/auth/googlehealth.mindfulness.writeonly
  https://www.googleapis.com/auth/googlehealth.profile.readonly https://www.googleapis.com/auth/googlehealth.health_metrics_and_measurements.writeonly
  https://www.googleapis.com/auth/googlehealth.ecg.readonly
